### ISSUE TITLE
template = #ig-template

### ISSUE THREAD

**Issue by keithboone** [HL7/fhir-shorthand#51]
When I add the line above to my ig.ini in ig-data folder, it doesn't get copied to the ig.ini for my input folder.  I have a workaround (which is to copy what it should be from a backup), but would love it if sushi let me use a local template.

**Comment by cmoesel** [comment]
Is it valid to specify a template with `#` as the first character?  I thought the convention was:
```
template = ig-template#template-version
```

As long as you're using SUSHI 0.10.0, the above will work -- but _starting_ with `#` will not work.  If this is a valid use case we'll have to fix it in SUSHI.  We need special-case code because many ini parser (including ours) think that `#` indicates the start of a comment, so it gets stripped.  We get around this by escaping the `#` before we parse it and then unescaping it after -- but our regex probably assumes a template name before the `#`.

**Comment by keithboone** [comment]
That's the syntax Lloyd used in UTG to use a template LOCAL to the project, rather than pulled from package registry.

**Comment by cmoesel** [comment]
Hmmm... OK.  We'll make an update to support that then.

**Comment by cmoesel** [comment]
This was resolved a long time ago.
